apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
spec:
  storageClassName: {{ .Values.storage.className }}
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.storage.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - db