apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-cars-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/distefano119ua/cicd-app-gitops.git
    targetRevision: main
    path: charts/backend-cars
    helm:
      releaseName: backend-cars

  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-app-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
